name: Feed Generator
on:
  schedule:
    - cron: "0 */2 * * *" #runs at every 2 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
          python dhyey01.py
          python drishti01.py          
          mv *.xml public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
