
name: RSS Feed Generator & Publisher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Trigger feed update
        timeout-minutes: 2
        env:
          READER_URL: ${{ secrets.READER_URL }}
        run: |
          if [[ -n "$READER_URL" ]]; then
            echo "Triggering feed update..."
            curl -L --retry 3 --silent --fail --max-time 30 "$READER_URL" || echo "Warning: Feed update request failed"
          else
            echo "No reader URL configured, skipping feed update"
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests feedparser
      - name: Wait for 3 minutes
        run: sleep 180 # 3 minutes * 60 seconds/minute
      - name: Run all feed generator scripts
        run: |
          python dhyey01.py
          python drishti01.py
          python rss_processor.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Move XML files to public/
        run: |
          mkdir -p public
          mv *.xml public/ || true

      - name: Upload RSS to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true

      - name: Print Processed RSS Feed URLs
        run: |
          echo "Your processed RSS feeds will be available at:"
          REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
          for file in public/*.xml; do
            fname=$(basename "$file")
            echo "https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/${fname}"
          done
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
