
name: Update feeds

on:
  schedule:
    - cron: "0 */1 * * *" # Every hour
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger feed update
        timeout-minutes: 3
        env:
          READER_URL: ${{ secrets.READER_URL }}
        run: |
          if [[ -n "$READER_URL" ]]; then
            echo "Triggering feed update..."
            curl -L --retry 3 --silent --fail --max-time 30 "$READER_URL" || echo "Warning: Feed update request failed"
          else
            echo "No reader URL configured, skipping feed update"
          fi